export interface LicitacaoDataDto {
  id_licitacao: string;
  titulo: string;
  descricao: string;
  url: string;
  data_criacao: Date;
  numero_controle_pncp: string;
  orgao_id: number;
  orgao_cnpj: string;
  orgao_nome: string;
  unidade_id: number;
  unidade_nome: string;
  esfera_id: string;
  esfera_nome: string;
  poder_id: string;
  poder_nome: string;
  municipio_id: number;
  municipio_nome: string;
  uf: string;
  modalidade_licitacao_id: number;
  modalidade_licitacao_nome: string;
  situacao_id: number;
  situacao_nome: string;
  id_tempo: number;
  data_publicacao: Date;
  ano: number;
  mes: number;
  cancelado: string;
  trimestre: number;
  valor_global: number;
  id_tipocontrato: number | string;
  tipocontrato: string;
  licitacao_items: string;
}
